// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0e9YwDgE-Btbz9zlOA6UZHcSpTYxFfk',
    appId: '1:958350959019:web:13a6fb69133409a59a72ee',
    messagingSenderId: '958350959019',
    projectId: 'flutter-firebase-9400f',
    authDomain: 'flutter-firebase-9400f.firebaseapp.com',
    storageBucket: 'flutter-firebase-9400f.firebasestorage.app',
    measurementId: 'G-LN6M0TZFCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPvzVkSzSoz49xxFAoBdjcZi09NHCF88',
    appId: '1:958350959019:android:96fb3aaa412629d99a72ee',
    messagingSenderId: '958350959019',
    projectId: 'flutter-firebase-9400f',
    storageBucket: 'flutter-firebase-9400f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvhdjK2a9cC_uRP2JH-95grUrLcd9NqsM',
    appId: '1:958350959019:ios:5006d86b9e14a6aa9a72ee',
    messagingSenderId: '958350959019',
    projectId: 'flutter-firebase-9400f',
    storageBucket: 'flutter-firebase-9400f.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvhdjK2a9cC_uRP2JH-95grUrLcd9NqsM',
    appId: '1:958350959019:ios:5006d86b9e14a6aa9a72ee',
    messagingSenderId: '958350959019',
    projectId: 'flutter-firebase-9400f',
    storageBucket: 'flutter-firebase-9400f.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm0e9YwDgE-Btbz9zlOA6UZHcSpTYxFfk',
    appId: '1:958350959019:web:7c8134f5bab7ce109a72ee',
    messagingSenderId: '958350959019',
    projectId: 'flutter-firebase-9400f',
    authDomain: 'flutter-firebase-9400f.firebaseapp.com',
    storageBucket: 'flutter-firebase-9400f.firebasestorage.app',
    measurementId: 'G-7ZDNLTQ5J3',
  );

}